/*
 * decaffeinate suggestions:
 * DS102: Remove unnecessary code created because of implicit returns
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/master/docs/suggestions.md
 */
// Generated by https://pagedraw.io/pages/11538
import React from 'react';


const render = function() {
    return React.createElement("div", {"className": "createlibrary-createlibrary-5"},
        React.createElement("style", {"dangerouslySetInnerHTML": ({__html: `\
@import url('https://fonts.googleapis.com/css?family=Lato:');

.createlibrary-createlibrary-5 {
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    background: rgba(79, 150, 95, 0);
}

.createlibrary-0 {
    display: flex;
    flex-shrink: 0;
}

.createlibrary-rectangle_3 {
    display: flex;
    flex-direction: column;
    padding-top: 5px;
    padding-bottom: 4px;
    border-radius: 30px;
    cursor: pointer;
    background: rgb(57, 150, 253);
}

.createlibrary-0-0-0 {
    display: flex;
    flex-shrink: 0;
    padding-left: 9px;
    padding-right: 9px;
}

.createlibrary-create_now_-0 {
    width: 66px;
    flex-shrink: 0;
    font-family: "Lato", sans-serif;
    color: rgb(255, 255, 255);
    font-size: 12px;
    line-height: 14px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
}

* {
    box-sizing: border-box;
}

body {
    margin: 0;
}

button:hover {
    cursor: pointer;
}

a {
    text-decoration: none;
    color: inherit;
}

.pd-onhover-parent >.pd-onhover {
    display: none;
}

.pd-onhover-parent:hover > * {
    display: none;
}

.pd-onhover-parent:hover > .pd-onhover {
    display: flex;
}

.pd-onactive-parent > .pd-onactive {
    display: none;
}

.pd-onactive-parent:active > * {
    display: none;
}

.pd-onactive-parent:active > .pd-onactive {
    display: flex;
}

.pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {
    display: none;
}\
`})}),  
        React.createElement("div", {"className": "createlibrary-0"},
            React.createElement("div", {"onClick": (this.props.onClick), "className": "createlibrary-rectangle_3"},
                React.createElement("div", {"className": "createlibrary-0-0-0"},
                    React.createElement("div", {"className": "createlibrary-create_now_-0"}, `\
Create now!\
`)
                )
            )
        )
    );
};

export default props => render.apply({props});
