/*
 * decaffeinate suggestions:
 * DS102: Remove unnecessary code created because of implicit returns
 * DS207: Consider shorter variations of null checks
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/master/docs/suggestions.md
 */
// Generated by https://pagedraw.io/pages/1470
let Addlistitem;
import React from 'react';
import createReactClass from 'create-react-class';

export default Addlistitem = createReactClass({
    displayName: 'Addlistitem',
    render() {
        return React.createElement("div", {"className": "pd-onactive-parent pd-onhover-parent addlistitem"},
          React.createElement("style", {"dangerouslySetInnerHTML": ({__html: `\
.addlistitem {
    display: flex;
    flex-grow: 1;
}

.addlistitem-_active-1 {
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    background: rgb(179, 179, 179);
}

.addlistitem-0-0 {
    display: flex;
    flex-shrink: 0;
}

.addlistitem-pointer-8 {
    display: flex;
    flex-direction: column;
    padding-top: 7px;
    padding-bottom: 7px;
    cursor: pointer;
    background: rgba(216, 216, 216, 0);
}

.addlistitem-0-0-0-0 {
    display: flex;
    flex-shrink: 0;
    padding-left: 16px;
    padding-right: 11px;
}

.addlistitem-0-0-0-0-0 {
    display: flex;
    flex-direction: column;
    padding-top: 6px;
    padding-bottom: 7px;
}

.addlistitem-0-0-0-0-0-0 {
    display: flex;
    flex-shrink: 0;
}

.addlistitem-label-6 {
    width: 213px;
    flex-shrink: 0;
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    color: #000000;
    font-size: 14px;
    line-height: normal;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: left;
    word-wrap: break-word;
}

.addlistitem-0-0-0-0-1 {
    margin-left: 7px;
    display: flex;
    width: 29px;
    height: 29px;
}

.addlistitem-rectangle_2 {
    display: flex;
    flex-direction: column;
    padding-top: 6px;
    padding-bottom: 6px;
    border-radius: 3px;
    background: rgb(193, 193, 193);
    flex-grow: 1;
}

.addlistitem-0-0-0-0-1-0-0-0 {
    display: flex;
    flex-shrink: 0;
    padding-left: 2px;
    padding-right: 3px;
}

.addlistitem-a_-1 {
    width: 24px;
    flex-shrink: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Helvetica', sans-serif;
    color: rgb(255, 255, 255);
    font-size: 14px;
    line-height: normal;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
}

.addlistitem-a-6 {
    display: flex;
    flex-direction: column;
    background: #FFFFFF;
    flex-grow: 1;
}

.addlistitem-1-0-0 {
    display: flex;
    flex-shrink: 0;
}

.addlistitem-pointer-7 {
    display: flex;
    flex-direction: column;
    padding-top: 7px;
    padding-bottom: 7px;
    cursor: pointer;
    background: rgba(216, 216, 216, 0);
}

.addlistitem-1-0-0-0-0 {
    display: flex;
    flex-shrink: 0;
    padding-left: 16px;
    padding-right: 11px;
}

.addlistitem-1-0-0-0-0-0 {
    display: flex;
    flex-direction: column;
    padding-top: 6px;
    padding-bottom: 7px;
}

.addlistitem-1-0-0-0-0-0-0 {
    display: flex;
    flex-shrink: 0;
}

.addlistitem-label-9 {
    width: 213px;
    flex-shrink: 0;
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    color: #000000;
    font-size: 14px;
    line-height: normal;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: left;
    word-wrap: break-word;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

.addlistitem-1-0-0-0-0-1 {
    margin-left: 7px;
    display: flex;
    width: 29px;
    height: 29px;
}

.addlistitem-rectangle_2-9 {
    display: flex;
    flex-direction: column;
    padding-top: 6px;
    padding-bottom: 6px;
    border-radius: 3px;
    background: rgb(193, 193, 193);
    flex-grow: 1;
}

.addlistitem-1-0-0-0-0-1-0-0-0 {
    display: flex;
    flex-shrink: 0;
    padding-left: 2px;
    padding-right: 3px;
}

.addlistitem-a_-9 {
    width: 24px;
    flex-shrink: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Helvetica', sans-serif;
    color: rgb(255, 255, 255);
    font-size: 14px;
    line-height: normal;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
}

.addlistitem-_hover-9 {
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    background: rgb(243, 243, 243);
}

.addlistitem-2-0 {
    display: flex;
    flex-shrink: 0;
}

.addlistitem-pointer-1 {
    display: flex;
    flex-direction: column;
    padding-top: 7px;
    padding-bottom: 7px;
    cursor: pointer;
    background: rgba(216, 216, 216, 0);
}

.addlistitem-2-0-0-0 {
    display: flex;
    flex-shrink: 0;
    padding-left: 16px;
    padding-right: 11px;
}

.addlistitem-2-0-0-0-0 {
    display: flex;
    flex-direction: column;
    padding-top: 6px;
    padding-bottom: 7px;
}

.addlistitem-2-0-0-0-0-0 {
    display: flex;
    flex-shrink: 0;
}

.addlistitem-label-7 {
    width: 213px;
    flex-shrink: 0;
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    color: #000000;
    font-size: 14px;
    line-height: normal;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: left;
    word-wrap: break-word;
}

.addlistitem-2-0-0-0-1 {
    margin-left: 7px;
    display: flex;
    width: 29px;
    height: 29px;
}

.addlistitem-rectangle_2-7 {
    display: flex;
    flex-direction: column;
    padding-top: 6px;
    padding-bottom: 6px;
    border-radius: 3px;
    background: rgb(193, 193, 193);
    flex-grow: 1;
}

.addlistitem-2-0-0-0-1-0-0-0 {
    display: flex;
    flex-shrink: 0;
    padding-left: 2px;
    padding-right: 3px;
}

.addlistitem-a_-7 {
    width: 24px;
    flex-shrink: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Helvetica', sans-serif;
    color: rgb(255, 255, 255);
    font-size: 14px;
    line-height: normal;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: center;
    word-wrap: break-word;
}

* {
    box-sizing: border-box;
}

body {
    margin: 0;
}

button:hover {
    cursor: pointer;
}

a {
    text-decoration: none;
    color: inherit;
}

.pd-onhover-parent >.pd-onhover {
    display: none;
}

.pd-onhover-parent:hover > * {
    display: none;
}

.pd-onhover-parent:hover > .pd-onhover {
    display: flex;
}

.pd-onactive-parent > .pd-onactive {
    display: none;
}

.pd-onactive-parent:active > * {
    display: none;
}

.pd-onactive-parent:active > .pd-onactive {
    display: flex;
}

.pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {
    display: none;
}\
`})}),  
          React.createElement("div", {"className": "pd-onactive addlistitem-_active-1"},
              React.createElement("div", {"className": "addlistitem-0-0"},
                  React.createElement("div", {"className": "addlistitem-pointer-8"},
                      React.createElement("div", {"className": "addlistitem-0-0-0-0"},
                          React.createElement("div", {"className": "addlistitem-0-0-0-0-0"},
                              React.createElement("div", {"className": "addlistitem-0-0-0-0-0-0"},
                                  React.createElement("div", {"className": "addlistitem-label-6"},
                                      ( this.props.label )
                                  )
                              )
                          ),
                          React.createElement("div", {"className": "addlistitem-0-0-0-0-1"},
                              ( ((this.props.keyCommand != null) && (this.props.keyCommand !== '')) ?
                                  React.createElement("div", {"className": "addlistitem-rectangle_2"},
                                      React.createElement("div", {"className": "addlistitem-0-0-0-0-1-0-0-0"},
                                          React.createElement("div", {"className": "addlistitem-a_-1"},
                                              ( this.props.keyCommand )
                                          )
                                      )
                                  ) : undefined
                              )
                          )
                      )
                  )
              )
          ),
          ( (("A") === "A") ?
              React.createElement("div", {"className": "addlistitem-a-6"},
                  React.createElement("div", {"className": "addlistitem-1-0-0"},
                      React.createElement("div", {"className": "addlistitem-pointer-7"},
                          React.createElement("div", {"className": "addlistitem-1-0-0-0-0"},
                              React.createElement("div", {"className": "addlistitem-1-0-0-0-0-0"},
                                  React.createElement("div", {"className": "addlistitem-1-0-0-0-0-0-0"},
                                      React.createElement("div", {"className": "addlistitem-label-9"},
                                          ( this.props.label )
                                      )
                                  )
                              ),
                              React.createElement("div", {"className": "addlistitem-1-0-0-0-0-1"},
                                  ( ((this.props.keyCommand != null) && (this.props.keyCommand !== '')) ?
                                      React.createElement("div", {"className": "addlistitem-rectangle_2-9"},
                                          React.createElement("div", {"className": "addlistitem-1-0-0-0-0-1-0-0-0"},
                                              React.createElement("div", {"className": "addlistitem-a_-9"},
                                                  ( this.props.keyCommand )
                                              )
                                          )
                                      ) : undefined
                                  )
                              )
                          )
                      )
                  )
              ) : undefined
          ),
          React.createElement("div", {"className": "pd-onhover addlistitem-_hover-9"},
              React.createElement("div", {"className": "addlistitem-2-0"},
                  React.createElement("div", {"className": "addlistitem-pointer-1"},
                      React.createElement("div", {"className": "addlistitem-2-0-0-0"},
                          React.createElement("div", {"className": "addlistitem-2-0-0-0-0"},
                              React.createElement("div", {"className": "addlistitem-2-0-0-0-0-0"},
                                  React.createElement("div", {"className": "addlistitem-label-7"},
                                      ( this.props.label )
                                  )
                              )
                          ),
                          React.createElement("div", {"className": "addlistitem-2-0-0-0-1"},
                              ( ((this.props.keyCommand != null) && (this.props.keyCommand !== '')) ?
                                  React.createElement("div", {"className": "addlistitem-rectangle_2-7"},
                                      React.createElement("div", {"className": "addlistitem-2-0-0-0-1-0-0-0"},
                                          React.createElement("div", {"className": "addlistitem-a_-7"},
                                              ( this.props.keyCommand )
                                          )
                                      )
                                  ) : undefined
                              )
                          )
                      )
                  )
              )
          )
      );
    }
});
