// TODO: This file was created by bulk-decaffeinate.
// Sanity-check the conversion and remove this comment.
/*
 * decaffeinate suggestions:
 * DS102: Remove unnecessary code created because of implicit returns
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/master/docs/suggestions.md
 */
// Generated by https://pagedraw.io/pages/5249
import React from 'react';


const render = () => React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "flexGrow": "1", "background": "rgb(255, 255, 255)"})},
    React.createElement("style", {"dangerouslySetInnerHTML": ({__html: `\
@import url('https://fonts.googleapis.com/css?family=Lato:');

* {
box-sizing: border-box;
}

body {
margin: 0;
}

button:hover {
cursor: pointer;
}

a {
text-decoration: none;
color: inherit;
}

.pd-onhover-parent >.pd-onhover {
display: none;
}

.pd-onhover-parent:hover > * {
display: none;
}

.pd-onhover-parent:hover > .pd-onhover {
display: flex;
}

.pd-onactive-parent > .pd-onactive {
display: none;
}

.pd-onactive-parent:active > * {
display: none;
}

.pd-onactive-parent:active > .pd-onactive {
display: flex;
}

.pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {
display: none;
}\
`})}),  
    React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0"})},
        React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "flexGrow": "1", "flexBasis": 0, "minHeight": "fit-content", "paddingBottom": 36, "borderRadius": 10, "boxShadow": "0px 5px 15px 0px rgba(0,0,0,0.07), 0px 15px 35px 0px rgba(50,50,93,0.10)", "background": "rgb(255, 255, 255)"})},
            React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0"})},
                React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "flexGrow": "1", "flexBasis": 0, "minHeight": "fit-content", "paddingTop": 20, "paddingBottom": 18, "background": "rgb(42, 42, 89)"})},
                    React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0"})},
                        React.createElement("div", {"style": ({"height": 0, "flexGrow": "0.49635036496350365", "flexBasis": 0})}),  
                        React.createElement("div", {"style": ({"width": 211, "flexShrink": "0", "fontFamily": "\"Lato\", sans-serif", "color": "rgb(255, 255, 255)", "fontSize": 22, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word"})}, `\
Individual\
`),
                        React.createElement("div", {"style": ({"height": 0, "flexGrow": "0.5036496350364964", "flexBasis": 0})}) 
                    )
                )
            ),
            React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "marginTop": 33, "justifyContent": "center"})},
                React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column"})},
                    React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "paddingLeft": 114, "paddingRight": 98})},
                        React.createElement("div", {"style": ({"width": 47, "flexShrink": "0", "fontFamily": "\"Lato\", sans-serif", "color": "rgb(6, 18, 44)", "fontSize": 40, "lineHeight": "50px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word"})}, `\
$0\
`),
                        React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "paddingTop": 10, "paddingBottom": 17})},
                            React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0"})},
                                React.createElement("div", {"style": ({"width": 17, "flexShrink": "0", "fontFamily": "\"Lato\", sans-serif", "color": "rgba(7, 14, 33, 0.5)", "fontSize": 19, "lineHeight": "normal", "letterSpacing": 0.4600000083446503, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word"})}, `\
*\
`)
                            )
                        )
                    ),
                    React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "marginTop": 6, "paddingLeft": 76, "paddingRight": 76})},
                        React.createElement("div", {"style": ({"width": 124, "flexShrink": "0", "fontFamily": "\"Lato\", sans-serif", "color": "rgba(7, 14, 33, 0.5)", "fontSize": 12, "lineHeight": "normal", "letterSpacing": 0.4600000083446503, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word"})}, `\
while in beta*\
`)
                    ),
                    React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "marginTop": 40, "paddingLeft": 107, "paddingRight": 107})},
                        React.createElement("div", {"style": ({"width": 62, "flexShrink": "0", "fontFamily": "\"Lato\", sans-serif", "color": "rgba(7, 14, 33, 0.5)", "fontSize": 12, "lineHeight": "normal", "letterSpacing": 0.4600000083446503, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word"})}, `\
INCLUDES\
`)
                    ),
                    React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "marginTop": 10})},
                        React.createElement("div", {"style": ({"width": 276, "flexShrink": "0", "fontFamily": "\"Lato\", sans-serif", "color": "rgb(6, 18, 44)", "fontSize": 17, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word"})},
                            React.createElement("div", null, "Code generation from designs"),
                            React.createElement("div", null, "Full access to all features"),
                            React.createElement("div", null, "Email and community support"),
                            React.createElement("div", null, "Unlimited private projects"),
                            React.createElement("div", null, " ")
                        )
                    ),
                    React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "marginTop": 31, "paddingLeft": 61, "paddingRight": 59})},
                        React.createElement("a", {"href": "/tutorials/basics", "style": ({"display": "flex"})},
                            React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "borderRadius": 4, "boxShadow": "0px 5px 15px 0px rgba(0,0,0,0.07), 0px 15px 35px 0px rgba(50,50,93,0.10)", "background": "rgb(42, 42, 89)", "flexGrow": "1"})},
                                React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "paddingLeft": 36, "paddingRight": 36})},
                                    React.createElement("div", {"style": ({"width": 84, "flexShrink": "0", "fontFamily": "\"Lato\", sans-serif", "color": "rgb(255, 255, 255)", "fontSize": 15, "lineHeight": "40px", "letterSpacing": 0.3308823, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word"})}, `\
Try it out\
`)
                                )
                            )
                        )
                    )
                )
            )
        )
    )
);

export default props => render.apply({props});
