/*
 * decaffeinate suggestions:
 * DS102: Remove unnecessary code created because of implicit returns
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/master/docs/suggestions.md
 */
// Generated by https://pagedraw.io/pages/5249
let Landingtopbar;
import React from 'react';
import createReactClass from 'create-react-class';

export default Landingtopbar = createReactClass({
    displayName: 'Landingtopbar',
    render() {
        return React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "flexGrow": "1"})},
          React.createElement("style", {"dangerouslySetInnerHTML": ({__html: `\
@import url('https://fonts.googleapis.com/css?family=Lato:');

* {
    box-sizing: border-box;
}

body {
    margin: 0;
}

button:hover {
    cursor: pointer;
}

a {
    text-decoration: none;
    color: inherit;
}

.pd-onhover-parent >.pd-onhover {
    display: none;
}

.pd-onhover-parent:hover > * {
    display: none;
}

.pd-onhover-parent:hover > .pd-onhover {
    display: flex;
}

.pd-onactive-parent > .pd-onactive {
    display: none;
}

.pd-onactive-parent:active > * {
    display: none;
}

.pd-onactive-parent:active > .pd-onactive {
    display: flex;
}

.pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {
    display: none;
}\
`})}),  
          React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "paddingLeft": 15})},
              React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "paddingBottom": 1})},
                  React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0"})},
                      React.createElement("a", {"href": "/", "style": ({"display": "flex"})},
                          React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "flexGrow": "1"})},
                              React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "paddingRight": 29})},
                                  React.createElement("img", {"src": "https://ucarecdn.com/f8b3ff29-bde2-4e98-b67e-bfa1f4cfbe04/", "style": ({"width": 30, "height": 25, "flexShrink": "0", "borderWidth": 0})}),  
                                  React.createElement("div", {"style": ({"width": 75, "flexShrink": "0", "marginLeft": 6, "fontFamily": "\"Lato\", sans-serif", "color": (this.props.white ? 'rgba(255, 255, 255, 0.8)' : '#06122C'), "fontSize": 17, "lineHeight": "25.5px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "left", "wordWrap": "break-word"})}, `\
Pagedraw\
`)
                              )
                          )
                      )
                  )
              ),
              React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "marginLeft": 117})},
                  React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0"})},
                      React.createElement("div", {"style": ({"width": 445, "height": 26, "flexShrink": "0", "position": "relative"})},
                          React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "flexGrow": "1", "position": "absolute", "top": 0, "left": 0})},
                              React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "paddingRight": 102})},
                                  React.createElement("a", {"href": "/tutorials/basics", "style": ({"flexShrink": "0", "display": "flex"})},
                                      React.createElement("div", {"style": ({"fontFamily": "\"Lato\", sans-serif", "color": (this.props.white ? 'rgba(255, 255, 255, 0.8)' : '#06122C'), "fontSize": 17, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word", "paddingRight": 0.1875, "flexGrow": "1"})}, `\
Get Started\
`)
                                  ),
                                  React.createElement("a", {"href": "https://documentation.pagedraw.io/", "style": ({"flexShrink": "0", "marginLeft": 52, "display": "flex"})},
                                      React.createElement("div", {"style": ({"fontFamily": "\"Lato\", sans-serif", "color": (this.props.white ? 'rgba(255, 255, 255, 0.8)' : '#06122C'), "fontSize": 17, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "left", "wordWrap": "break-word", "paddingRight": 0.59375, "flexGrow": "1"})}, `\
Documentation\
`)
                                  ),
                                  React.createElement("a", {"href": "https://medium.com/pagedraw", "style": ({"flexShrink": "0", "marginLeft": 50, "display": "flex"})},
                                      React.createElement("div", {"style": ({"fontFamily": "\"Lato\", sans-serif", "color": (this.props.white ? 'rgba(255, 255, 255, 0.8)' : '#06122C'), "fontSize": 17, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "left", "wordWrap": "break-word", "paddingRight": 0.71875, "flexGrow": "1"})}, `\
Blog\
`)
                                  )
                              )
                          ),
                          React.createElement("a", {"href": "https://github.com/Pagedraw/pagedraw", "style": ({"flexGrow": "1", "position": "absolute", "top": 0, "left": 390, "display": "flex"})},
                              React.createElement("div", {"style": ({"fontFamily": "\"Lato\", sans-serif", "color": (this.props.white ? 'rgba(255, 255, 255, 0.8)' : '#06122C'), "fontSize": 17, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word", "paddingRight": 0.015625, "flexGrow": "1"})}, `\
GitHub\
`)
                          )
                      )
                  )
              ),
              React.createElement("a", {"href": "/apps", "style": ({"flexShrink": "0", "marginLeft": 195, "display": "flex"})},
                  React.createElement("div", {"style": ({"width": 74, "fontFamily": "Helvetica, Arial, sans-serif", "color": (this.props.white ? 'rgba(255, 255, 255, 0.8)' : '#06122C'), "fontSize": 17, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "left", "wordWrap": "break-word", "flexGrow": "1"})},
                      ("Sign in → ")
                  )
              )
          )
      );
    }
});
