// TODO: This file was created by bulk-decaffeinate.
// Sanity-check the conversion and remove this comment.
/*
 * decaffeinate suggestions:
 * DS102: Remove unnecessary code created because of implicit returns
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/master/docs/suggestions.md
 */
// Generated by https://pagedraw.io/pages/5249
let Landingtopbar;
import React from 'react';
import createReactClass from 'create-react-class';

export default Landingtopbar = createReactClass({
    displayName: 'Landingtopbar',
    render() {
        return (
            <div style={{"display": "flex", "flexDirection": "column", "flexGrow": "1"}}>
                <style
                    dangerouslySetInnerHTML={{__html: `\
          @import url('https://fonts.googleapis.com/css?family=Lato:');

          * {
              box-sizing: border-box;
          }

          body {
              margin: 0;
          }

          button:hover {
              cursor: pointer;
          }

          a {
              text-decoration: none;
              color: inherit;
          }

          .pd-onhover-parent >.pd-onhover {
              display: none;
          }

          .pd-onhover-parent:hover > * {
              display: none;
          }

          .pd-onhover-parent:hover > .pd-onhover {
              display: flex;
          }

          .pd-onactive-parent > .pd-onactive {
              display: none;
          }

          .pd-onactive-parent:active > * {
              display: none;
          }

          .pd-onactive-parent:active > .pd-onactive {
              display: flex;
          }

          .pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {
              display: none;
          }\
          `}} />
                <div style={{"display": "flex", "flexShrink": "0", "paddingLeft": 15}}>
                    <div
                        style={{"display": "flex", "flexDirection": "column", "paddingBottom": 1}}>
                        <div style={{"display": "flex", "flexShrink": "0"}}>
                            <a href="/" style={{"display": "flex"}}>
                                <div style={{"display": "flex", "flexDirection": "column", "flexGrow": "1"}}>
                                    <div style={{"display": "flex", "flexShrink": "0", "paddingRight": 29}}>
                                        <img
                                            src="https://ucarecdn.com/f8b3ff29-bde2-4e98-b67e-bfa1f4cfbe04/"
                                            style={{"width": 30, "height": 25, "flexShrink": "0", "borderWidth": 0}} />
                                        <div
                                            style={{"width": 75, "flexShrink": "0", "marginLeft": 6, "fontFamily": "\"Lato\", sans-serif", "color": (this.props.white ? 'rgba(255, 255, 255, 0.8)' : '#06122C'), "fontSize": 17, "lineHeight": "25.5px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "left", "wordWrap": "break-word"}}>
                                            {`\
          Pagedraw\
          `}
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div style={{"display": "flex", "flexDirection": "column", "marginLeft": 117}}>
                        <div style={{"display": "flex", "flexShrink": "0"}}>
                            <div
                                style={{"width": 445, "height": 26, "flexShrink": "0", "position": "relative"}}>
                                <div
                                    style={{"display": "flex", "flexDirection": "column", "flexGrow": "1", "position": "absolute", "top": 0, "left": 0}}>
                                    <div style={{"display": "flex", "flexShrink": "0", "paddingRight": 102}}>
                                        <a href="/tutorials/basics" style={{"flexShrink": "0", "display": "flex"}}>
                                            <div
                                                style={{"fontFamily": "\"Lato\", sans-serif", "color": (this.props.white ? 'rgba(255, 255, 255, 0.8)' : '#06122C'), "fontSize": 17, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word", "paddingRight": 0.1875, "flexGrow": "1"}}>
                                                {`\
          Get Started\
          `}
                                            </div>
                                        </a>
                                        <a
                                            href="https://documentation.pagedraw.io/"
                                            style={{"flexShrink": "0", "marginLeft": 52, "display": "flex"}}>
                                            <div
                                                style={{"fontFamily": "\"Lato\", sans-serif", "color": (this.props.white ? 'rgba(255, 255, 255, 0.8)' : '#06122C'), "fontSize": 17, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "left", "wordWrap": "break-word", "paddingRight": 0.59375, "flexGrow": "1"}}>
                                                {`\
          Documentation\
          `}
                                            </div>
                                        </a>
                                        <a
                                            href="https://medium.com/pagedraw"
                                            style={{"flexShrink": "0", "marginLeft": 50, "display": "flex"}}>
                                            <div
                                                style={{"fontFamily": "\"Lato\", sans-serif", "color": (this.props.white ? 'rgba(255, 255, 255, 0.8)' : '#06122C'), "fontSize": 17, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "left", "wordWrap": "break-word", "paddingRight": 0.71875, "flexGrow": "1"}}>
                                                {`\
          Blog\
          `}
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <a
                                    href="https://github.com/Pagedraw/pagedraw"
                                    style={{"flexGrow": "1", "position": "absolute", "top": 0, "left": 390, "display": "flex"}}>
                                    <div
                                        style={{"fontFamily": "\"Lato\", sans-serif", "color": (this.props.white ? 'rgba(255, 255, 255, 0.8)' : '#06122C'), "fontSize": 17, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word", "paddingRight": 0.015625, "flexGrow": "1"}}>
                                        {`\
          GitHub\
          `}
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    <a
                        href="/apps"
                        style={{"flexShrink": "0", "marginLeft": 195, "display": "flex"}}>
                        <div
                            style={{"width": 74, "fontFamily": "Helvetica, Arial, sans-serif", "color": (this.props.white ? 'rgba(255, 255, 255, 0.8)' : '#06122C'), "fontSize": 17, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "left", "wordWrap": "break-word", "flexGrow": "1"}}>
                            {"Sign in → "}
                        </div>
                    </a>
                </div>
            </div>
        );
    }
});
