// TODO: This file was created by bulk-decaffeinate.
// Sanity-check the conversion and remove this comment.
/*
 * decaffeinate suggestions:
 * DS102: Remove unnecessary code created because of implicit returns
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/master/docs/suggestions.md
 */
// Generated by https://pagedraw.io/pages/5249
import React from 'react';

import Studentscard from './studentscard';
import Individualcard from './individualcard';
import Companycard from './companycard';


const render = () => React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "flexGrow": "1"})},
    React.createElement("style", {"dangerouslySetInnerHTML": ({__html: `\


* {
box-sizing: border-box;
}

body {
margin: 0;
}

button:hover {
cursor: pointer;
}

a {
text-decoration: none;
color: inherit;
}

.pd-onhover-parent >.pd-onhover {
display: none;
}

.pd-onhover-parent:hover > * {
display: none;
}

.pd-onhover-parent:hover > .pd-onhover {
display: flex;
}

.pd-onactive-parent > .pd-onactive {
display: none;
}

.pd-onactive-parent:active > * {
display: none;
}

.pd-onactive-parent:active > .pd-onactive {
display: flex;
}

.pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {
display: none;
}\
`})}),  
    React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0"})},
        React.createElement("div", {"style": ({"flexShrink": "0", "display": "flex", "flexDirection": "column", "minWidth": 348})},
            React.createElement(Studentscard, null) 
        ),
        React.createElement("div", {"style": ({"flexShrink": "0", "marginLeft": 33, "display": "flex", "flexDirection": "column", "minWidth": 348})},
            React.createElement(Individualcard, null) 
        ),
        React.createElement("div", {"style": ({"flexShrink": "0", "marginLeft": 33, "display": "flex", "flexDirection": "column", "minWidth": 348})},
            React.createElement(Companycard, null) 
        )
    )
);

export default props => render.apply({props});
