# Generated by https://pagedraw.io/pages/5249
React = require 'react'


render = ->
    React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "flexGrow": "1", "background": "rgb(255, 255, 255)"})},
        React.createElement("style", {"dangerouslySetInnerHTML": (__html: """
            @import url('https://fonts.googleapis.com/css?family=Lato:');
            
            * {
                box-sizing: border-box;
            }
            
            body {
                margin: 0;
            }
            
            button:hover {
                cursor: pointer;
            }
            
            a {
                text-decoration: none;
                color: inherit;
            }
            
            .pd-onhover-parent >.pd-onhover {
                display: none;
            }
            
            .pd-onhover-parent:hover > * {
                display: none;
            }
            
            .pd-onhover-parent:hover > .pd-onhover {
                display: flex;
            }
            
            .pd-onactive-parent > .pd-onactive {
                display: none;
            }
            
            .pd-onactive-parent:active > * {
                display: none;
            }
            
            .pd-onactive-parent:active > .pd-onactive {
                display: flex;
            }
            
            .pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {
                display: none;
            }
        """)}),  
        React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0"})},
            React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "flexGrow": "1", "flexBasis": 0, "minHeight": "fit-content", "paddingBottom": 36, "borderRadius": 10, "boxShadow": "0px 5px 15px 0px rgba(0,0,0,0.07), 0px 15px 35px 0px rgba(50,50,93,0.10)", "background": "rgb(255, 255, 255)"})},
                React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0"})},
                    React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "flexGrow": "1", "flexBasis": 0, "minHeight": "fit-content", "paddingTop": 20, "paddingBottom": 18, "background": "rgb(100, 100, 211)"})},
                        React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0"})},
                            React.createElement("div", {"style": ({"height": 0, "flexGrow": "0.4883720930232558", "flexBasis": 0})}),  
                            React.createElement("div", {"style": ({"width": 262, "flexShrink": "0", "fontFamily": "\"Lato\", sans-serif", "color": "rgb(255, 255, 255)", "fontSize": 22, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word"})}, """
                                Students and Open Source
"""),
                            React.createElement("div", {"style": ({"height": 0, "flexGrow": "0.5116279069767442", "flexBasis": 0})}) 
                        )
                    )
                ),
                React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "marginTop": 33})},
                    React.createElement("div", {"style": ({"height": 0, "flexGrow": "0.49504950495049505", "flexBasis": 0})}),  
                    React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column"})},
                        React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "paddingLeft": 100, "paddingRight": 100})},
                            React.createElement("div", {"style": ({"width": 47, "flexShrink": "0", "fontFamily": "\"Lato\", sans-serif", "color": "rgb(6, 18, 44)", "fontSize": 40, "lineHeight": "50px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word"})}, """
                                $0
""")
                        ),
                        React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "marginTop": 6, "paddingLeft": 86, "paddingRight": 85})},
                            React.createElement("div", {"style": ({"width": 76, "flexShrink": "0", "fontFamily": "\"Lato\", sans-serif", "color": "rgba(7, 14, 33, 0.5)", "fontSize": 12, "lineHeight": "normal", "letterSpacing": 0.4600000083446503, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word"})}, """
                                per month
""")
                        ),
                        React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "marginTop": 40, "paddingLeft": 93, "paddingRight": 92})},
                            React.createElement("div", {"style": ({"width": 62, "flexShrink": "0", "fontFamily": "\"Lato\", sans-serif", "color": "rgba(7, 14, 33, 0.5)", "fontSize": 12, "lineHeight": "normal", "letterSpacing": 0.4600000083446503, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word"})}, """
                                INCLUDES
""")
                        ),
                        React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "marginTop": 10})},
                            React.createElement("div", {"style": ({"width": 247, "flexShrink": "0", "fontFamily": "\"Lato\", sans-serif", "color": "rgb(6, 18, 44)", "fontSize": 17, "lineHeight": "26px", "letterSpacing": 0, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word"})},
                                React.createElement("div", null, "Free forever"),
                                React.createElement("div", null, "Code generation from designs"),
                                React.createElement("div", null, "Full access to all features"),
                                React.createElement("div", null, "Unlimited public projects"),
                                React.createElement("div", null, " ")
                            )
                        ),
                        React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "marginTop": 31, "paddingLeft": 47, "paddingRight": 44})},
                            React.createElement("a", {"href": "/tutorials/basics", "style": ({"display": "flex"})},
                                React.createElement("div", {"style": ({"display": "flex", "flexDirection": "column", "borderRadius": 4, "boxShadow": "0px 5px 15px 0px rgba(0,0,0,0.07), 0px 15px 35px 0px rgba(50,50,93,0.10)", "background": "rgb(100, 100, 211)", "flexGrow": "1"})},
                                    React.createElement("div", {"style": ({"display": "flex", "flexShrink": "0", "paddingLeft": 36, "paddingRight": 36})},
                                        React.createElement("div", {"style": ({"width": 84, "flexShrink": "0", "fontFamily": "\"Lato\", sans-serif", "color": "rgb(255, 255, 255)", "fontSize": 15, "lineHeight": "40px", "letterSpacing": 0.3308823, "fontWeight": "normal", "fontStyle": "normal", "textDecoration": "none", "textAlign": "center", "wordWrap": "break-word"})}, """
                                            Try it out
""")
                                    )
                                )
                            )
                        )
                    ),
                    React.createElement("div", {"style": ({"height": 0, "flexGrow": "0.504950495049505", "flexBasis": 0})}) 
                )
            )
        )
    )

module.exports = (props) -> render.apply({props})
